name: NuGet Publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: enter your name
        required: true


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
